name: Build

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: StockMarketAPI

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # Make the wrapper runnable on Linux even if committed from Windows
      - name: Prepare Gradle wrapper
        run: |
          test -f gradlew || { echo "gradlew missing in StockMarketAPI/"; exit 1; }
          sed -i 's/\r$//' gradlew
          chmod +x gradlew || true
          bash -n gradlew || true   # quick syntax check

      - name: Build
        run: bash ./gradlew build -x test --no-daemon
