name: SonarCloud

on: [push, pull_request]

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Wait for Postgres port
        run: |
          for i in {1..30}; do
            (echo > /dev/tcp/127.0.0.1/5432) >/dev/null 2>&1 && break
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Run tests + coverage
        run: ./gradlew --no-daemon clean test jacocoTestReport -i

      - name: SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew --no-daemon sonarqube \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=dido1043 \
            -Dsonar.projectKey=dido1043_StockMarket \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Upload coverage & test reports (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            build/reports/jacoco/test/jacocoTestReport.xml
            build/reports/tests/test/index.html
            build/test-results/test/*.xml