name: SonarCloud

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  sonar:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: StockMarketAPI

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # make the wrapper runnable on Linux even if committed from Windows
      - name: Prepare Gradle wrapper
        run: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew || true

      - name: Build & test (with coverage)
        run: bash ./gradlew clean test jacocoTestReport --no-daemon

      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v5.3.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=dido1043
            -Dsonar.projectKey=dido1043_StockMarket
            -Dsonar.projectName=StockMarketAPI
            -Dsonar.projectBaseDir=StockMarketAPI
            -Dsonar.sources=src/main
            -Dsonar.tests=src/test
            -Dsonar.java.binaries=build/classes,build/classes/java/main
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
